services:
  db:
    container_name: ai-agent-postgresql 
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ai-agent-postgresql:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    container_name: ai-agent-nest-backend
    build: .
    restart: always
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - backend
    command: npm run start:dev

volumes:
  ai-agent-postgresql:

networks:
  backend: